### ISSUE TITLE
cr2w options: -a is excluding array data

### ISSUE THREAD

**Issue by khafir** [rfuzzo/CP77Tools#45]
Reproduceable behavior, examples linked to pastebin.

{cr2w -a -p "/path/to/file"} excludes content from {cr2w -c -p "/path/to/file"}. In the examples I've seen and can reproduce, -a is excluding array value data that -c displays. I've tried to investigate the options here on the Git page and am unsure as to whether this is by intent or not. If this is working as intended please disregard. Additionally, I do not see an option with cr2w or pack to update a target with modified (cr2w extracted) chunk data. If this feature is present please point me in the right direction.

Target: \basegame_1_engine\base\gameplay\gui\fullscreen\main_menu\ui_character_presets\ui_preset_female_corpo.charcustpreset

-a result: https://pastebin.com/tFP5NdBm
-c result: https://pastebin.com/LUaifXzv

Shell programmer by trade here, you've done some amazing work. Thank you.

**Comment by rfuzzo** [comment]
Thank you! 
yes -a is excluding array data, that is kinda intended, but should probably be fixed. (It was intended because -a was just a debug option for me, but I agree for it to be more useful, it should also include array data)

about the other issue: editing cr2w files (or serialising back from json) is not implemented yet. I’ll add another issue.

I’ll add a help-wanted and enhancement tag to this issue. 

thanks!

**Comment by khafir** [comment]
> Thank you!
> yes -a is excluding array data, that is kinda intended, but should probably be fixed. (It was intended because -a was just a debug option for me, but I agree for it to be more useful, it should also include array data)
> 
> about the other issue: editing cr2w files (or serialising back from json) is not implemented yet. I’ll add another issue.
> 
> I’ll add a help-wanted and enhancement tag to this issue.
> 
> thanks!

Thank you and I eagerly await the feature!

**Comment by rfuzzo** [comment]
This is not needed anymore as we have full engine classes now
